### ISSUE TITLE
Option to set description

### ISSUE THREAD

**Issue by rnett** [nexus-actions/release-nexus-staging-repo#1]
The description of staging repositories seems to be updated each operation.  This means that if you set a nice description during creation, it is overwritten by the default during release or closing.  It would be nice to have the ability to set the description on this action, as well.

**Comment by rnett** [comment]
Looking at the code, it seems like this should be done, or rather it should use the input description (set earlier).    However, this does not work, I get descriptions like `Close comgithubrnett-1048` (`comgithubrnett-1048` is the id) after closing (I'm using `close_only`), so it seems like it's using the ID instead of the previous description.

**Comment by romainbsl** [comment]
You're right, we could provide a way to set your own description.
If you feel confortable you can submit a PR, otherwise we will do this as soon as possible.

**Comment by rnett** [comment]
Are there docs for the sonnatype API somewhere?  If there are, or if it's the same as `create` I can.  I'll try stuff if not, but I'm not sure when I'd get to it.

**Comment by romainbsl** [comment]
Some stuffs can be found here:
- https://oss.sonatype.org/nexus-staging-plugin/default/docs/index.html
- https://repository.sonatype.org/nexus-restlet1x-plugin/default/docs/index.html

But you could just add a param to the action and share an environment variable to pass to the different jobs ?

**Comment by romainbsl** [comment]
published https://github.com/nexus-actions/release-nexus-staging-repo/releases/tag/v1.2
